# Netlify Configuration for Data Profiler Frontend

[build]
  # Build command
  command = "cd frontend && npm install && npm run build"
  
  # Publish directory (Vite builds to 'dist' by default)
  publish = "frontend/dist"
  
  # Base directory (optional, but helps Netlify find your frontend)
  base = "frontend"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (optional - set these in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"

# Headers for better performance (optional)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

